### ISSUE TITLE
Cookies are not updated when they are changed by the server

### ISSUE THREAD

**Issue by wattry** [bendotcodes/cookies#281]
When using cookies for authentication we have a cookie that is sent down by the server that is cleared when a user logs out. However, when they are removed the value is not updated and thus the react component cannot render the new state.

**Comment by vcombey** [comment]
same problem here

**Comment by achompolov** [comment]
update on this?

**Comment by eXon** [comment]
Unfortunately there is no cross-browser reliant way to know cookies have been changed. Any idea on how we could fix the API?

**Comment by eXon** [comment]
[cookies.onChanged](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/cookies/onChanged) could be used when supported by the browser. However, we would need to do polling (maybe every second) if the browser does not support it.

**Comment by amaster507** [comment]
If you go this route with polling, please make it customizable somewhere in a config option so polling can be enabled/disabled and the interval can be set to a custom time.

**Comment by meros** [comment]
In my case I call fetch which updates a cookie. I know when this call happens, so a simple exposed refresh or reload would be great.

**Comment by bogdaniel** [comment]
Cookies should only be set by the server.
