### ISSUE TITLE
Can't call setCookie with typescript and useCookies hook

### ISSUE THREAD

**Issue by laugre** [bendotcodes/cookies#301]
Hi there,
I don't understand how to make it work with typescript.

Do I make something wrong with that code ?

```
const [setCookie, removeCookie] = useCookies<string>(['token']);
setCookie('token', 'tokenvalue', {path: '/'});
```
![Capture d’écran 2021-11-05 à 14 40 27](https://user-images.githubusercontent.com/5321589/140519433-fd015a5e-29be-4a51-8ac0-50ab695cb5e2.png)

Thx

**Comment by gulllberg** [comment]
According to the docs the useCookies signature is [cookies, setCookie, removeCookie]
const [cookies, setCookie, removeCookie] = useCookies(['cookie-name']);

So if you want to skip the first argument do
const [_, setCookie, removeCookie] = useCookies(['cookie-name']);

**Comment by laugre** [comment]
Right, 
I finally used universal-cookie instead...
But thx I missed that, I'll back to react-cookie.
For me better approach to use that react hook instead of const cookies = new Cookies();
