### ISSUE TITLE
Universal cookie change callback returns value as string

### ISSUE THREAD

**Issue by KasparRosin** [bendotcodes/cookies#302]
I have an issue where the addChangeListener callback is returning the value stringified due to this line without attempting to parse it first.
https://github.com/reactivestack/cookies/blob/master/packages/universal-cookie/src/Cookies.ts#L69

What is the expected behaviour? I would expect it have the same functionality as get().
I would use the readCookie util inside the emit function.

**Comment by eXon** [comment]
This is fixed in 6.0.0
