### ISSUE TITLE
useCookies() hook does not seem to react to cookie updates on xhr requests

### ISSUE THREAD

**Issue by anking** [bendotcodes/cookies#304]
I have the following scenario:

-My application always calls server to set session cookies and upon initial load the cookies are read correctly by react-cookie
-When session is about to expire i click a button "extend session" which in turn calls the server and extends the session updating cookies by setting the appropriate header (I can see the cookie/expiration updates in devtools)
- useCookies() hook, however still returns the old cookie values.

I'm trying to avoid calling setCookie if the server already does this, am i doing smth wrong?

[Add]

It looks like even if i expicitly call setCookie() when i do the "extend session" I still end up seeing old cookie values inside my original session component.

[Add2]

It also appear that useCookies() still returns old values even if I manually add a new cookie with devtools

**Comment by anking** [comment]
I ended up using "universal-cookie" instead of "react-cookie" as I was unable to get it to work. I think it has something in it's implementation of hooks that just doesn't work right

**Comment by gradisarjoze** [comment]
Any updates on this? I am facing the same issue.

**Comment by anking** [comment]
@gradisarjoze unfortunately I wasn't able to find a quick solution for the problem and opted out of using react-cookies for now. I doubt that this is a react-cookie problem but could be caused by some browser/cookie policies that I don't have too much knowledge about. Universal cookies is a good workaround in a meantime

**Comment by krishnaTORQUE** [comment]
I am also facing the same issue.

**Comment by Mystilund** [comment]
Same here. For more context, the cookie is erased on backend side on logout, but if I login it's still in the `react-cookie` memory. But strange thing, in a component the `useCookies` hook is used directly and my cookie is not present (so it works well), but when it is in a custom hook (with the cookie used in an `useEffect`), the value is still set. If it can help :v:

**Comment by tworkool** [comment]
Almost a year later and this still does not work!!!

**Comment by eXon** [comment]
This was unfortunately a flaw of the library because it cannot know if other parties were changing the cookies. When changing cookies on the server, with v6 you can trigger an update by calling `updateCookies()`, which is now the 4th paramater in useCookies. See the readme for more info.

If this is still an issue in v6, please open a new issue.
