### ISSUE TITLE
Cookies not working on Safari (MacOs) and iOS's browsers

### ISSUE THREAD

**Issue by Xam-Mlr** [bendotcodes/cookies#322]
Hi, i'm about to finish my project in React so i'm doing some tests on iPhone. That was a full fail so i checked with a virtual console and i noticed that the react-cookies doesn't work. 
(I precise it works well on my macOs laptop with Opera)
Is there any solutions ?
Thanks

**Comment by tadej321** [comment]
I figured out that passing the options object to the `setCookie` function with `secure` set to `true`, the cookie is not set in storage. I made it work by setting the `secure` to `false` or removing the field altogether.

**Comment by hinciler** [comment]
If I changed `secure` to `false` it works on Safari but this time, it doesn't work on other Browsers.

> I figured out that passing the options object to the `setCookie` function with `secure` set to `true`, the cookie is not set in storage. I made it work by setting the `secure` to `false` or removing object item altogether.

**Comment by jordan-jarolim** [comment]
As @hinciler said, it is one way or the other. Secure true/false only works on Safari or other browsers, but not all of them at the same time. I think this is a critical bug in this library.

**Comment by jordan-jarolim** [comment]
I found out that as soon as you remove sameSite=none it works both in chrome and safari

**Comment by damankonspot** [comment]
@jordan-jarolim mine doesn't work even after sameSite=none

**Comment by eXon** [comment]
Unfortunately the library allows you to set the right properties for Safari but you will have to figure out which one it is for your use case.
