### ISSUE TITLE
`universal-cookie` ESM support

### ISSUE THREAD

**Issue by thisismydesign** [bendotcodes/cookies#328]
`universal-cookie` is the dependency of `@nuxtjs/apollo` which [uses the latest version](https://github.com/nuxt-modules/apollo/blob/83e46428540ca57dd84c99453a5e454dbc40946b/package.json#L29) 4.0.4.

Due to a change to [ESM in Nuxt 3](https://v3.nuxtjs.org/guide/concepts/esm/), `universal-cookie` now has to be transpiled, see: https://github.com/nuxt-community/apollo-module/issues/435

Going forward it would be great if `universal-cookie` would be ESM-compatible.

**Comment by eXon** [comment]
The latest version should be ESM compatible. If you're still having issues, feel free to re-open this.
