### ISSUE TITLE
`universal-cookie` path param does not add cookie if page navigated to via client side nav

### ISSUE THREAD

**Issue by cmugla** [bendotcodes/cookies#340]
## What's up

Hey all, we are seeing the cookie not properly added to the browser if you redirect to the path via client side navigation.

Example: cookie params
```
{
    domain: CONFIG.cookieDomain,
    expires: null, 
    path: `/super-secret-page`, 
    sameSite: 'lax',
    secure: true, 
}
```

Repro:
- Land on `/regular-page`, set a cookie on click of a button with `path: '/'`
- client side navigate to `/super-secret-page`
- set another cookie on click of a button with `path` set as above
- open cookies in dev tools

Expected:
- the new cookie would appear 

Actual:
- the new cookie isn't there

## Questions
Is this behavior by design? If so, would you provide more information around how `path` is compared?

**Comment by KarlaLGA** [comment]
This is happening to me too. I had to redirect the full page with `window.location.href=` to make sure the cookie is being saved in the path I need.

**Comment by eXon** [comment]
This should be fixed in v6, please re-open if it's not the case.
