### ISSUE TITLE
access_token does not list in the cookie

### ISSUE THREAD

**Issue by hhpr98** [bendotcodes/cookies#342]
I am getting the cookie by
```
const ACCESS_TOKEN = 'access_token' as string;

function AppRouter(): JSX.Element {
  const [cookie, setCookie] = useCookies([ACCESS_TOKEN]);

  useEffect(() => {
    console.log(cookie);
  }, [cookie]);
```

From the applications tab we can see the access_token
![image](https://user-images.githubusercontent.com/39483775/209643300-af2a3ca9-70ad-4696-875d-f17adf4e271b.png)
But looks like it is not appeared when I use react-cookie
![image](https://user-images.githubusercontent.com/39483775/209643411-6e074a04-f2e9-4dca-b1c3-4fd80af34594.png)

Is it a bug?

**Comment by S-P-Ks** [comment]
Facing the same thing, it is not showing the cookie or is unable to fetch the cookie on the Client Side.

**Comment by S-P-Ks** [comment]
I found that if you are setting the cookie as a HTTP ONLY then if was unable to catch the cookie on the development env.

**Comment by eXon** [comment]
It is expected that the browser is unable to read HTTP only cookies.
