### ISSUE TITLE
Redundant Promise usage

### ISSUE THREAD

**Issue by integrer** [bendotcodes/cookies#344]
Promise callback actually has no effect because it has been executing in-place synchronously.
https://github.com/reactivestack/cookies/blob/4d12ae55e91a04d958b9c17f94ba152c951730a3/packages/universal-cookie/src/Cookies.ts#L21-L23
If it intended to be executed asynchronously, it should be rewritten like
```javascript
 Promise.resolve().then(() => {
   this.HAS_DOCUMENT_COOKIE = hasDocumentCookie();
 });
```
or unwrapped at all.

**Comment by eXon** [comment]
Promise has been removed
