### ISSUE TITLE
React-cookie - When cookie expires, creating a new cookie wont work until page refresh or creating cookie a second time

### ISSUE THREAD

**Issue by KevinFerreira** [bendotcodes/cookies#347]
Noticed in my app that when setting a cookie initially, it works perfectly fine. However, once that cookie expires, and the user tries to create a new one, it doesn't work initially. There were two ways of temporarily fixing this:
- Refresh the page
- Click the button again in the component that creates the cookie

I saw [this StackOverflow post](https://stackoverflow.com/a/73079525/13637417) that, while not as relevant, led me to believe it could possibly be a bug in the react-cookie repo (maybe).

However, the way to fix this was to set a `maxAge` in addition to the `expires` when creating a cookie

**Issue:**

Broken method where the 2nd cookie -- after the first cookie expired -- wouldn't work until the browser refresh or the second click in my component:
```
  const createCookie = () => {
    setCookies('local_host_admin', jwt, {
      expires: cookieExpiryDate, // this was set to 2 minutes to test (i.e. 120 seconds after `now`)
      path: '/',
      domain: `localhost`,
    })
  }
```

**Temporary Solution:**

The solution that just needed `maxAge` (in seconds) to be added:
```
  const createCookie = () => {
    setCookies('local_host_admin', jwt, {
      expires: cookieExpiryDate,  // this was set to 2 minutes to test (i.e. 120 seconds after `now`)
      path: '/',
      domain: `localhost`,
      maxAge: 120, << the cookie now gets created on first try after the first cookie had expired
    })
  }
```

Keep in mind, both the `expiry` date and `maxAge` are technically the same (`expiry` = now + 2 minutes & `maxAge` = 120 seconds.

Hoping that this opens up some sort of investigation into why this might be the case, or maybe I'm actually missing something on my end, regardless I hope this temporary fix helps some people in the meantime

**Comment by eXon** [comment]
This should be fixed in v6, please re-open if it's not the case.
