### ISSUE TITLE
397,170 weekly npm downloads, 9 stars on GH?

### ISSUE THREAD

**Issue by AntonOfTheWoods** [bendotcodes/cookies#383]
Am I missing something? Did this project get hacked?

**Comment by eXon** [comment]
@AntonOfTheWoods You're actually missing the 1M+ weekly downloads for univeral-cookie as well... 😂 

This repo unfortunately lost all his stars less than one week ago when it was made private by mistake when creating the .github/settings.yml file. 

At least I did not lost [54k stars like this one](https://httpie.io/blog/stardust).

**Comment by AntonOfTheWoods** [comment]
You get a star for that :-)
