### ISSUE TITLE
React-cookie: pass options in useCookies

### ISSUE THREAD

**Issue by Armanio** [bendotcodes/cookies#386]
Hi! First thank for handful lib!

When i use useCookies i cant pass options for parsing cookies.
For example i need disable default cookie parsing (i save in cookies big number like 1691590724652002030230)

I think we need could pass doNotParse option in 
https://github.com/bendotcodes/cookies/blob/9fff6a06c9395ca802289239e8861aaadcc3db73/packages/react-cookie/src/useCookies.tsx#L19

**Comment by eXon** [comment]
It is currently unsupported but I will gladly review a PR if you would like to add the option.
