### ISSUE TITLE
Unable to use the universal-cookies constructor in Node 18

### ISSUE THREAD

**Issue by rosslh** [bendotcodes/cookies#393]
When I try to create a new Cookies instance, I get the error: `(TypeError: Cookies is not a constructor)`

Here is a minimal reproduction of the issue: https://replit.com/@rosslh/Universal-cookies-repro#index.js

**Comment by DaniilIsupov** [comment]
I have the same problem in Node.js ESM

```
node -v
v20.5.1

npm -v
9.8.0
```

**Comment by ajaxbo360** [comment]
i had same problem when i deploy my app

**Comment by ajaxbo360** [comment]
my node version is 18 i downgrade universal-cookie to version 4.0.4 and its working fine

**Comment by eXon** [comment]
This has been fixed in v7. If you upgrade and it still does not work, you can re-open this issue.
