### ISSUE TITLE
No GitHub release for version 6.0.0

### ISSUE THREAD

**Issue by thomasjm** [bendotcodes/cookies#402]
Version 6.0.0 exists on NPM but not on the GitHub releases, which is confusing.

And it seems the `CHANGELOG.md` file was deprecated, so there's no easy way to know what happened in 6.0.0. (It seems to have broken something for me in server-side rendering, but that's another issue.)

**Comment by eXon** [comment]
The release was existing but somehow wasn't showing up in the UI. I had to update the description with no change and now you should be able to see it. 

For the SSR issue, #425 should fix it in the next release.
