### ISSUE TITLE
react-cookie: Stricter returned cookie types

### ISSUE THREAD

**Issue by rtrembecky** [bendotcodes/cookies#417]
Hi, so in work I patched the `react-cookie` package for us to provide `string | Record<string, unknown> | undefined` type for cookies instead of `any`. It's a single-line change here:

https://github.com/bendotcodes/cookies/blob/main/packages/react-cookie/src/useCookies.tsx#L6

```ts
- export default function useCookies<T extends string, U = { [K in T]?: any }>(
+ export default function useCookies<T extends string, U = { [K in T]?: string | Record<string, unknown> | undefined }>( 
```

I'm not sure what's the best type here, but the above provided a bit more security for us. We can check `typeof x === 'string'` and `typeof x === 'object'` to narrow it down in our components.

I'm not planning to do a PR, but raising it here as someone might find this helpful.

**Comment by eXon** [comment]
Hi @rtrembecky 

Thank you for pointing it out. While this is a change that really make sense to me, this is a big breaking change that can only be considered in a major release. I will be taking that into consideration.
