### ISSUE TITLE
Nuxt3 error: Cookie is not a constructor

### ISSUE THREAD

**Issue by kissu** [bendotcodes/cookies#422]
I'm not fully sure how to explain this one further, but it looks like the v6 is having some issues regarding SSR + [VueUse's `useCookies`](https://vueuse.org/integrations/usecookies/) as shown here: https://github.com/vueuse/vueuse/issues/3589#issue-2011133053

Using `v4.0.4` works well but I thought a report on the issue would be welcome. 🤗

**Comment by lermontex** [comment]
I also have the same problem when trying to use universal-cookie 6.0.1

```
node-1   | TypeError: Cookies is not a constructor
node-1   |     at createServerPersistedState (file:///srv/app/dist/server/entry-server.js:2822:5)
node-1   |     at render (file:///srv/app/dist/server/entry-server.js:2837:13)
node-1   |     at file:///srv/app/server.js:101:17
```

I'm using Vue 3 + Vite + Express

universal-cookie is used as Cookie for pinia + pinia-plugin-persistedstate

At the moment I had to revert to version 4.0.4 - works without errors

https://www.npmjs.com/package/pinia
https://www.npmjs.com/package/pinia-plugin-persistedstate

**Comment by eXon** [comment]
This has been fixed in v7. If you upgrade and it still does not work, you can re-open this issue.
