### ISSUE TITLE
Cannot read a refreshed cookie

### ISSUE THREAD

**Issue by SimonStAmand** [bendotcodes/cookies#459]
This feels like a bug, but I am not sure. It seems that handling a refreshed cookie is lacking? I can receive and read a cookie just fine, but it fails to read the refreshed cookie.

The only 'fix' I found is to do a dirty cheat.

```
const [token, setToken, removeCookie] = useCookies([AUTH_TOKEN_KEY]);

...

useEffect(() => {
  // Done a second before the cookie is expired
  identityAPI
    .useRefreshAuthToken(token.auth_token)
    .then((newToken) => {
      removeCookie(AUTH_TOKEN_KEY);
      setToken(AUTH_TOKEN_KEY, newToken.data);
    })
    .catch(() => console.error("Token refresh failed"));
}, [isSessionExpired]);
```

**Comment by eXon** [comment]
Hi @SimonStAmand 

Can you please provider:

 - An example replicating the issue
 - Your version of react-cookie and universal-cookie
 - Your cookie settings when setting it
 - Your domain/protocol/path when reading it

When your API return the cookie, it should be able to detect the change.

**Comment by SimonStAmand** [comment]
Nevermind. It works. I did a bunch of other changes and everything is ok now.
