### ISSUE TITLE
How to retrieve a Cookie's Max-Age

### ISSUE THREAD

**Issue by hariprasath-jd** [bendotcodes/cookies#464]
## version
` "universal-cookie": "^7.0.2"`

- in a react project

can I?

Thanks in advance for your help

**Comment by eXon** [comment]
This is unfortunately impossible to do. When getting the browser's cookies, they only prive you with a list of key/value. However, the expiration is unknown.

**Comment by hariprasath-jd** [comment]
Thanks @eXon
