### ISSUE TITLE
react-cookie types export for require is incorrect

### ISSUE THREAD

**Issue by josephearl** [bendotcodes/cookies#477]
The exports in the package.json for require point to a types file that does not exist:

```
"exports": {
    ".": {
      "import": {
        "types": "./esm/index.d.mts",
        "default": "./esm/index.mjs"
      },
      "require": {
        "types": "./cjs/index.d.mts",
        "default": "./cjs/index.js"
      },
      "default": "./cjs/index.js"
    }
  },
```

`./cjs/index.d.mts` does not exist - for require it should be `/cjs/index.d.ts` 

<img width="233" alt="Screenshot 2024-03-31 at 20 39 32" src="https://github.com/bendotcodes/cookies/assets/2513147/a0716e4b-7d43-4931-a37b-8f89c0f5f5bf">

**Comment by eXon** [comment]
While fixing ESM I broke CJS, it's fixed in 7.1.3
