### ISSUE TITLE
Could not find a declaration file for module react-cookie error

### ISSUE THREAD

**Issue by SeyoungYang-GGQ** [bendotcodes/cookies#479]
Hello, I'm encountering a type error while using react-cookie in Next.js. How can I resolve this?

```
import { useCookies } from 'react-cookie';

TS7016: Could not find a declaration file for module  react-cookie .
Desktop/project/front-next-intelligence-page/node_modules/react-cookie/cjs/index.js
implicitly has an  any  type.
Try  npm i --save-dev @types/react-cookie  if it exists or add a new declaration (.d.ts) file containing  declare module 'react-cookie';
```

**Comment by eXon** [comment]
@SeyoungYang-GGQ What version are you using? A regression was introduced in 7.1.2 that broke TypeScript for CJS builds. Are you having the same issue with 7.1.3 (it's just been released)

**Comment by SeyoungYang-GGQ** [comment]
@eXon 
I was using version 7.1.2 and just updated to 7.1.4. The issue no longer occurs. Thank you.
